# https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup
# dbt is set up to run on your BigQuery project. Change the project and dataset names as needed.

dbt_olist: # dbt_demo name. This is where dbt looks for from dbt_project.yml -> find the named profile here. Can also be overwritten by dbt run --profiles. See dbt run --help for more info
  target: jaffle_sql # default target for profile, points to 1 of the output below # define target in dbt CLI via --target
  outputs:
    threads: 1
    location: US
    priority: interactive
    jaffle_sql:
      type: bigquery
      method: service-account 
      keyfile: /Users/taysk/sctp/Project/dsai-brazilian-ecommerce-f611ef10e5c8.json
      project: "dsai-brazilian-ecommerce" # GCP project id
      dataset: "dbt_olist"
      retries: 2
  config:
    send_anonymous_usage_stats: False