version: 1
default_environment: dev
project_id: 50e426ee-19cc-4cd8-853f-e7d7eadad487
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
        - entity: olist_customers
          path: ../data/olist_customers_dataset_cleansed.csv
          encoding: utf-8-sig 
          keys: [customer_id]
        - entity: olist_geolocations
          path: ../data/olist_geolocation_dataset_cleansed.csv
          encoding: utf-8-sig
          keys: [geolocation_zip_code_prefix]
        - entity: olist_order_items
          path: ../data/olist_order_items_dataset_cleansed.csv
          encoding: utf-8-sig
          keys: [order_id, order_item_id]
        - entity: olist_order_payments
          path: ../data/olist_order_payments_dataset_cleansed.csv
          encoding: utf-8-sig
          keys: [order_id, payment_sequential]
        - entity: olist_order_reviews
          path: ../data/olist_order_reviews_dataset_cleansed.csv
          encoding: utf-8-sig
          keys: [review_id, order_id]
        - entity: olist_orders
          path: ../data/olist_orders_dataset_cleansed.csv
          encoding: utf-8-sig
          keys: [order_id]                   
        - entity: olist_products
          path: ../data/olist_products_dataset_cleansed.csv
          encoding: utf-8-sig
          keys: [product_id]                                  
        - entity: olist_sellers
          path: ../data/olist_sellers_dataset_cleansed.csv
          encoding: utf-8-sig
          keys: [seller_id]        
        - entity: product_category_name_translation
          path: ../data/product_category_name_translation_cleansed.csv
          encoding: utf-8-sig 
          keys: [product_category_name]       
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      project: meltano-learn-461903
      dataset: olist_raw
      credentials_path: /home/ongkokle/SCTP/SCTP-DSF1-Team5/03 - Code/credentials/meltano-learn-461903-deb8bae09cbe.json
      method: batch_job
      batch_size: 1000000 
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      overwrite: true
