version: 2

models:
  - name: fact_order_items
    description: "Fact table for order_items."
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null